version: 2
updates:
  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "hbahadorzadeh"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore(deps):"
      prefix-development: "chore(deps):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "hbahadorzadeh"
    commit-message:
      prefix: "ci:"
      include: "scope"
