run:
  timeout: 5m
  go: "1.24"
  skip-dirs:
    - vendor
  skip-files:
    - ".*_test.go$"

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused

issues:
  exclude-rules:
    - path: "_test\\.go$"
      linters:
        - errcheck
        - gosec
    - path: "example/"
      linters:
        - errcheck

severity:
  default-severity: error
  rules:
    - linters:
        - govet
      severity: error
