language: go

go:
  - "1.10.x"

before_install:
  - go get -v github.com/hbahadorzadeh/stunning
  - openssl req -x509 -newkey rsa:4096 -keyout server.key -out server.crt -days 365 <<EOL

EOL

script:
  - go test
  - go build
