language: go

go:
  - "1.10.x"

before_install:
  - go get -v github.com/hbahadorzadeh/stunning
  - echo -e "\n\n\n\n\n" | openssl req -x509 -newkey rsa:4096 -keyout server.key -out server.crt -days 365

script:
  - go test
  - go build
